=== krishemenway/PlaylistGenerator/PlaylistGenerator/Pools.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Pool" minOccurs="1" maxOccurs="unbounded" type="Pool" />
      </xs:sequence>
      <xs:attribute type="FileType" name="FileType" />
      <xs:attribute type="xs:int" name="max" />
      <xs:attribute type="Mode" name="Mode" />
    </xs:complexType>
  </xs:element>
  
  <xs:simpleType name="FileType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="mpcpl" />
      <xs:enumeration value="pls" />
      <xs:enumeration value="wpl" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Mode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SingleRandom" />
      <xs:enumeration value="MultiRandom" />
      <xs:enumeration value="LinearPlay" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Pool">
    <xs:sequence>
      <xs:element name="Directory" minOccurs="0" maxOccurs="unbounded" type="Location" />
      <xs:element name="Video" minOccurs="0" maxOccurs="unbounded" type="Location" />
    </xs:sequence>
    <xs:attribute name="mode" type="Mode" />
  </xs:complexType>

  <xs:complexType name="Location">
    <xs:attribute name="regex" type="xs:string" />
    <xs:attribute name="location" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== krishemenway/PlaylistGenerator/PlaylistGenerator/poolinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Playlist xsi:schemaLocation="D:\Programs\C#\PlaylistGenerator\PlaylistGenerator\Pools.xsd" xmlns:xsi="" FileType="wpl" mode="SingleRandom" max="250">
	<Pool>
		<Directory location="F:\TV Shows\South Park" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Home Movies" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Family Guy" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Futurama" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Comedy Central Presents" />
		<Directory location="F:\TV Shows\Icons" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Flight of the Conchords" />
		<Directory location="F:\TV Shows\Firefly" />
	</Pool>
	<Pool>
		<Directory location="F:\TV Shows\Dilbert" />
		<Directory location="F:\TV Shows\Better Off Ted" />
		<Directory location="F:\TV Shows\Community" />
		<Directory location="F:\TV Shows\It's Always Sunny In Philadelphia" />
		<Directory location="F:\TV Shows\Arrested Development" />
	</Pool>
	<Pool>
		<Directory location="F:\Movies" />
	</Pool>
</Playlist>
